// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/qinrui/design-model/proxy-model/pkg"
)

// Injectors from wire.go:

func NewLogger() *pkg.Logger {
	algorithm := pkg.NewAlgorithm()
	logger := pkg.NewLogger(algorithm)
	return logger
}
