// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/qinrui/go-design-model/adapter-model/pkg"
)

// Injectors from wire.go:

func NewDbAdapter() *pkg.TiDBAdapter {
	tiDB := pkg.NewTiDB()
	tiDBAdapter := pkg.NewTiDBAdapter(tiDB)
	return tiDBAdapter
}

// wire.go:

var MageDB = wire.NewSet(pkg.NewSql, pkg.NewTiDB)
