// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/qinrui/design-model/bridge-model/pkg/level"
	"github.com/qinrui/design-model/bridge-model/pkg/sender"
)

// Injectors from wire.go:

func NewWarningSender() level.ILevel {
	phoneSender := sender.NewPhoneSender()
	iLevel := level.NewWarning(phoneSender)
	return iLevel
}

// wire.go:

var MageSet = wire.NewSet(sender.NewMessageSender, sender.NewPhoneSender)
